### ISSUE TITLE
pythonw ENOENT error on windows

### ISSUE THREAD

**Issue by joerocklin** [wakatime/atom-wakatime#64]
Atom Version 1.8.0
atom-wakatime version: 6.0.9
Error displayed: `[WakaTime] [WARN] [wakatime.coffee:445] Error: spawn pythonw ENOENT`

Python34 is in my path, I get the same results when I start atom via the start menu or via `atom .` in a CLI.

With debugging logging turned on I can see that wakatime starts, checks the version of the wakatime-cli, and then hits the `ENOENT` error when trying to call the `cli.py` script. I can open a new powershell and copy the command from the developer console into the shell and it runs without error (log messages show up in `~/.wakatime.log`).

Is there anything else I can provide to help figure out what's going on?

(Edited to add the specific error message)

**Comment by alanhamlett** [comment]
Maybe we have to check the output from the `pythonw --version` command before accepting that path as working.

**Comment by joerocklin** [comment]
`pythonw --version` has no output (and no errors)
`python --version` outputs: `Python 3.4.3`

**Comment by alanhamlett** [comment]
Should be fixed in v6.0.10, but can you test to make sure?

**Comment by joerocklin** [comment]
Nope - same thing happening.

**Comment by alanhamlett** [comment]
Did you restart Atom after the upgrade? It only finds the Python binary on startup.

**Comment by joerocklin** [comment]
At this point I've restarted atom and restarted the system. I checked with another machine (also windows) which doesn't have the problem to see how python was installed (via chocolatey) and removed/reinstalled python on the problem system (and restarted the system). The new python is in the path (`python -V` returns 3.5.1) and I'm still getting the same `ENOENT` error in atom.

**Comment by joerocklin** [comment]
Some more data: I added some more debugging to the local version of the wakatime plugin to print the output of the python version testing when searching for locations (added in [this method](https://github.com/wakatime/atom-wakatime/blob/master/lib/wakatime.coffee#L229)). The output is:
```
[WakaTime] [DEBUG] [wakatime.coffee:252] Testing pythonw --version
[WakaTime] [DEBUG] [wakatime.coffee:255] stdout: Python 3.5.1
[WakaTime] [DEBUG] [wakatime.coffee:256] stderr: 
```
And it then proceeds to check for updates/etc. When I open a file (a ruby file in this case, though I'm not sure that makes any difference) and save, I then get:

```
[WakaTime] [DEBUG] [wakatime.coffee:424] pythonw C:\Users\<user>\.atom\packages\wakatime\lib\wakatime-master\wakatime\cli.py --file D:\workspace\cookbooks\ceph-chef\metadata.rb --plugin atom-wakatime/6.0.10 --lineno 15 --verbose
[WakaTime] [WARN] [wakatime.coffee:450] Error: spawn pythonw ENOENT
```

**Comment by joerocklin** [comment]
And I just noticed something very strange: when I opened the code for the wakatime plugin (via the `view code` button on the plugin settings page), I **do not** get the error for the plugin. I tried adding a few other projects to this new window and all works just fine.

This obviously isn't a great workaround, and might even present more questions than answers at this point...

**Comment by alanhamlett** [comment]
Does the file `C:\Users\<user>\.atom\packages\wakatime\lib\wakatime-master\wakatime\cli.py` exist?

Maybe the ENOENT error is for that file instead of pythonw?

**Comment by joerocklin** [comment]
The `cli.py` file does exist in that location. I double checked this process by closing all editor windows (and making sure no processes were lingering) and duplicating the behavior.

Perhaps even more strangely: if I exit atom while I only have wakatime source open, then open atom (which opens back to the wakatime source) then all is fine. Opening a new window and getting my project added, and I have no errors. If I exit atom such that when it starts again it opens my project, then the errors start again.

Is there a way to put the wakatime cli tools into a debug mode to see if there's some extra details about the error? Or do you think this is some strange atom-internals issue?

**Comment by joerocklin** [comment]
It also appears that I can have atom start in the failed state, open a new window, add my project and things work. But if I restart atom the errors show up again.

**Comment by alanhamlett** [comment]
Is this still happening or has it been fixed in the latest version of Atom or WakaTime?

**Comment by joerocklin** [comment]
I've stopped using atom so cannot comment on if this is still a problem.

**Comment by alanhamlett** [comment]
Ok, I'll close this for cleanup.
